back-end/config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :sneakers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

back-end/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

back-end/app/models/review.rb
class Review < ApplicationRecord
    belongs_to :sneaker
end

back-end/app/models/sneaker.rb
class Sneaker < ApplicationRecord
    has_many :reviews
end

back-end/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

back-end/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
    render json: @reviews
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:title, :comment, :sneaker_id)
    end
end

back-end/app/controllers/sneakers_controller.rb
class SneakersController < ApplicationController
  before_action :set_sneaker, only: [:show, :edit, :update, :destroy]

  # GET /sneakers
  # GET /sneakers.json
  def index
    @sneakers = Sneaker.all
    render json: @sneakers
  end

  # GET /sneakers/1
  # GET /sneakers/1.json
  def show
  end

  # GET /sneakers/new
  def new
    @sneaker = Sneaker.new
  end

  # GET /sneakers/1/edit
  def edit
  end

  # POST /sneakers
  # POST /sneakers.json
  def create
    @sneaker = Sneaker.new(sneaker_params)

    respond_to do |format|
      if @sneaker.save
        format.html { redirect_to @sneaker, notice: 'Sneaker was successfully created.' }
        format.json { render :show, status: :created, location: @sneaker }
      else
        format.html { render :new }
        format.json { render json: @sneaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sneakers/1
  # PATCH/PUT /sneakers/1.json
  def update
    respond_to do |format|
      if @sneaker.update(sneaker_params)
        format.html { redirect_to @sneaker, notice: 'Sneaker was successfully updated.' }
        format.json { render :show, status: :ok, location: @sneaker }
      else
        format.html { render :edit }
        format.json { render json: @sneaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sneakers/1
  # DELETE /sneakers/1.json
  def destroy
    @sneaker.destroy
    respond_to do |format|
      format.html { redirect_to sneakers_url, notice: 'Sneaker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sneaker
      @sneaker = Sneaker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sneaker_params
      params.require(:sneaker).permit(:name, :brand)
    end
end

back-end/app/helpers/application_helper.rb
module ApplicationHelper
end

back-end/app/helpers/reviews_helper.rb
module ReviewsHelper
end

back-end/app/helpers/sneakers_helper.rb
module SneakersHelper
end

back-end/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SneakerReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

back-end/app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>

  <div class="field">
    <%= form.label :sneaker_id %>
    <%= form.number_field :sneaker_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

back-end/app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

back-end/app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Comment</th>
      <th>Sneaker</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.title %></td>
        <td><%= review.comment %></td>
        <td><%= review.sneaker_id %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

back-end/app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

back-end/app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>Sneaker:</strong>
  <%= @review.sneaker_id %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

back-end/app/views/sneakers/_form.html.erb
<%= form_with(model: sneaker, local: true) do |form| %>
  <% if sneaker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sneaker.errors.count, "error") %> prohibited this sneaker from being saved:</h2>

      <ul>
      <% sneaker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

back-end/app/views/sneakers/edit.html.erb
<h1>Editing Sneaker</h1>

<%= render 'form', sneaker: @sneaker %>

<%= link_to 'Show', @sneaker %> |
<%= link_to 'Back', sneakers_path %>

back-end/app/views/sneakers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sneakers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Brand</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sneakers.each do |sneaker| %>
      <tr>
        <td><%= sneaker.name %></td>
        <td><%= sneaker.brand %></td>
        <td><%= link_to 'Show', sneaker %></td>
        <td><%= link_to 'Edit', edit_sneaker_path(sneaker) %></td>
        <td><%= link_to 'Destroy', sneaker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sneaker', new_sneaker_path %>

back-end/app/views/sneakers/new.html.erb
<h1>New Sneaker</h1>

<%= render 'form', sneaker: @sneaker %>

<%= link_to 'Back', sneakers_path %>

back-end/app/views/sneakers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sneaker.name %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @sneaker.brand %>
</p>

<%= link_to 'Edit', edit_sneaker_path(@sneaker) %> |
<%= link_to 'Back', sneakers_path %>